# Generated by Django 4.1.7 on 2023-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ecole_user_remove_choise_question_delete_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='ecole',
            name='description',
            field=models.CharField(blank='true', max_length=500),
        ),
    ]
